name: Run vunit tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sstaehli/nvc-vunit:latest
    steps:
      - uses: actions/checkout@v4
      - name: Run unit tests
        working-directory: ./test
        run: |
          . /opt/venv/bin/activate
          python3 ./run.py